# Generated by Django 5.1.6 on 2025-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='kursning nomi')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('created_ed', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_ed', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'kurs',
                'verbose_name_plural': 'kurslar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='tuliq ismi')),
                ('phone_number', models.CharField(max_length=13, verbose_name='telefon numer')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('created_ed', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_ed', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('kurs', models.ManyToManyField(related_name='students', to='configapp.kurs', verbose_name='kurs')),
            ],
            options={
                'verbose_name': 'talaba',
                'verbose_name_plural': 'talabalar',
                'ordering': ['full_name'],
            },
        ),
    ]
