# Generated by Django 5.1.6 on 2025-02-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='is_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_bool',
            field=models.BooleanField(default=True),
        ),
    ]
